Update deploy-ami0.yml
edit the NEW_AMI part

diff --git a/.github/workflows/deploy-ami0.yml b/.github/workflows/deploy-ami0.yml
--- a/.github/workflows/deploy-ami0.yml
+++ b/.github/workflows/deploy-ami0.yml
@@ -60,15 +60,23 @@ jobs:
       - name: Refresh ASG
         env:
             ASG_NAME: "schedemy01-ASG"
+            NEW_AMI_ID: ${{ env.AMI_ID }}
+            LT_NAME: "schedemy01-template"
         run: |
-          echo "Updating ASG $ASG_NAME with new AMI: ${{ env.AMI_ID }}"
+          echo "Updating ASG $ASG_NAME with new AMI: $NEW_AMI"
           
+          # Check if the ID is empty before proceeding
+          if [ -z "$NEW_AMI_ID" ]; then
+            echo "Error: NEW_AMI_ID is empty. The Packer build step failed to export it."
+            exit 1
+          fi
+         
           # 1. Create a new Launch Template Version with the new AMI
     
           aws ec2 create-launch-template-version \
-            --launch-template-name schedemy01-template \
+            --launch-template-name $LT_NAME \
             --source-version '$Latest' \
-            --launch-template-data "{\"ImageId\":\"${{ env.AMI_ID }}\"}"
+            --launch-template-data "{\"ImageId\":\"$NEW_AMI\"}"
 
           # 2. Tell ASG to start an Instance Refresh
           # This slowly replaces instances. MinHealthyPercentage=50 means at least half stay up.
